RE_HAND_ID = r"Winning\s*Poker\s*Network\s*Game\s*(#[0-9]*)\s*:\s*No\s*Limit\s*Holdem\s*(\(\d*\/\d*\))\s*(\[.*\])"
#RE_SEATS = r"Seats:\s*([1-9]*)"
RE_PLAYERS = r"(Seat)\s*(\d*):\s*(.*)\s*\(([0-9,]*)\)"
RE_DEALER = r"Button\s*is\s*seat\s*(\d*)"
RE_SB = r"(.*):\s*(posts\s*small\s*blind|raises\s*all-in)\s*([0-9,]*)"
RE_BB = r"(.*):\s*(posts\s*big blind|raises\s*all-in)\s*([0-9,]*)"
RE_ANTE = r"(.*):\s*antes\s*([0-9,]*)"
RE_HERO = r"(.*):\s*(dealt)\s*(\[.*\])"
RE_FLOP_H = r"\*\*\*.*\*\*\*\s*(\[.*\])"
RE_ACT = r"(.*): (bets|raises|folds|calls|checks|pulls\s*back\s*uncalled\s*bet|mucks)(.*)"
RE_TURN_H = r"\*\*\*.*\*\*\*\s*\[.*\]\s*(\[.*\])"
RE_RIVER_H = r"\*\*\*.*\*\*\*\s*\[.*\]\s*\[.*\]\s*(\[.*\])"
RE_SUMM_RAKEPOT = r"Pot:\s*([0-9,]*)\s*\|\s*Rake:\s*([0-9,]*)\s*\|"
RE_SUMM_BOARD = r"(Board):\s*(\[.*\])"
RE_SUMM_L = r"Seat\s*(\d*):\s*(.*)\s*(won|lost)\s*([\-0-9,]*)\s*(\[.*\])?\s*(.*)?"
RE_ALL_IN = r"(all-in)?([0-9,]*)"

